server:
  port: 5001
spring:
  messages:
    encoding: UTF-8
  jackson:
    date-format: dd MMMM yyyy HH:mm
    time-zone: Asia/Tashkent
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/saiga
    password: this_is_your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        enable_lazy_load_no_trans: true
telegram:
  botToken: 6225643427:AAEflrHOn9z452Re6wvcE4X2Z57OppPpMIU
  botUrl: bot6225643427:AAEflrHOn9z452Re6wvcE4X2Z57OppPpMIU
  botUsername: saiga_nk_bot
  groupId: -1001527780938
  groupName: saiga_nk