server:
  port: 3000
spring:
  jackson:
    date-format: dd MMMM yyyy HH:mm
    time-zone: Asia/Tashkent
  datasource:
    username: bbcyllqh
    url: jdbc:postgresql://arjuna.db.elephantsql.com/bbcyllqh
    password: wbje9GcsM8TD2aVYFzcjKrNEy9Dwn8F-
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        enable_lazy_load_no_trans: true


# postgres://bbcyllqh:wbje9GcsM8TD2aVYFzcjKrNEy9Dwn8F-@arjuna.db.elephantsql.com/bbcyllqh